export const languages = [
  { name: "English", sub: "English", locale: "en-IN", greeting: "Hello!" },
  { name: "தமிழ்", sub: "Tamil", locale: "ta-IN", greeting: "வணக்கம்!" },
  { name: "हिन्दी", sub: "Hindi", locale: "hi-IN", greeting: "नमस्ते!" },
  { name: "తెలుగు", sub: "Telugu", locale: "te-IN", greeting: "నమస్కారం!" },
  { name: "മലയാളം", sub: "Malayalam", locale: "ml-IN", greeting: "നമസ്കാരം!" },
];
const words = {
  English: {
    next: "Continue",
    back: "Back",
    unknown: "I don’t know",
    speak: "Speak",
    tap: "Tap",
    helper: "Helper",
    where: "Where is your pain or problem?",
    mode: "How would you like to tell your story?",
    yes: "Yes, correct",
    change: "Change something",
    send: "Send to doctor",
    understood: "Here’s what I understood",
    answer: "Your answer",
    listen: "Listen to question",
  },
  தமிழ்: {
    next: "தொடரவும்",
    back: "பின்செல்",
    unknown: "எனக்குத் தெரியாது",
    speak: "பேசுங்கள்",
    tap: "தேர்ந்தெடுங்கள்",
    helper: "உதவியாளர்",
    where: "எங்கு வலி அல்லது பிரச்சனை உள்ளது?",
    mode: "எப்படிப் பதிலளிக்க விரும்புகிறீர்கள்?",
    yes: "ஆம், சரி",
    change: "மாற்றவும்",
    send: "மருத்துவருக்கு அனுப்பவும்",
    understood: "நாங்கள் புரிந்துகொண்டவை",
    answer: "உங்கள் பதில்",
    listen: "கேள்வியைக் கேளுங்கள்",
  },
  हिन्दी: {
    next: "आगे बढ़ें",
    back: "वापस",
    unknown: "मुझे नहीं पता",
    speak: "बोलें",
    tap: "चुनें",
    helper: "सहायक",
    where: "दर्द या परेशानी कहाँ है?",
    mode: "आप कैसे जवाब देना चाहेंगे?",
    yes: "हाँ, सही है",
    change: "बदलाव करें",
    send: "डॉक्टर को भेजें",
    understood: "हमने यह समझा",
    answer: "आपका जवाब",
    listen: "सवाल सुनें",
  },
  తెలుగు: {
    next: "కొనసాగించండి",
    back: "వెనక్కి",
    unknown: "నాకు తెలియదు",
    speak: "మాట్లాడండి",
    tap: "ఎంచుకోండి",
    helper: "సహాయకుడు",
    where: "నొప్పి లేదా సమస్య ఎక్కడ ఉంది?",
    mode: "మీరు ఎలా సమాధానం ఇవ్వాలనుకుంటున్నారు?",
    yes: "అవును, సరైనది",
    change: "మార్చండి",
    send: "వైద్యునికి పంపండి",
    understood: "మేము అర్థం చేసుకున్నది",
    answer: "మీ సమాధానం",
    listen: "ప్రశ్న వినండి",
  },
  മലയാളം: {
    next: "തുടരുക",
    back: "തിരികെ",
    unknown: "എനിക്കറിയില്ല",
    speak: "സംസാരിക്കുക",
    tap: "തിരഞ്ഞെടുക്കുക",
    helper: "സഹായി",
    where: "വേദനയോ പ്രശ്നമോ എവിടെയാണ്?",
    mode: "എങ്ങനെ മറുപടി നൽകാൻ ആഗ്രഹിക്കുന്നു?",
    yes: "അതെ, ശരിയാണ്",
    change: "മാറ്റുക",
    send: "ഡോക്ടർക്ക് അയയ്ക്കുക",
    understood: "ഞങ്ങൾ മനസ്സിലാക്കിയത്",
    answer: "നിങ്ങളുടെ മറുപടി",
    listen: "ചോദ്യം കേൾക്കുക",
  },
};
const questions = {
  தமிழ்: [
    "என்ன உடல்நலப் பிரச்சனை உள்ளது?",
    "இது எப்போது தொடங்கியது?",
    "எவ்வளவு சிரமமாக உள்ளது?",
    "எப்போதும் உள்ளதா அல்லது வந்து போகிறதா?",
    "வேறு ஏதேனும் அறிகுறிகள் உள்ளனவா?",
    "இப்போது என்ன மருந்துகள் எடுக்கிறீர்கள்?",
    "உங்களுக்கு ஏதேனும் ஒவ்வாமை உள்ளதா?",
    "முந்தைய உடல்நலப் பிரச்சனைகள் உள்ளனவா?",
  ],
  हिन्दी: [
    "आपको क्या परेशानी हो रही है?",
    "यह कब शुरू हुआ?",
    "यह आपको कितना परेशान कर रहा है?",
    "क्या यह लगातार रहता है या आता-जाता है?",
    "क्या कोई और लक्षण हैं?",
    "आप अभी कौन सी दवाइयाँ ले रहे हैं?",
    "क्या आपको कोई एलर्जी है?",
    "क्या कोई पिछला स्वास्थ्य इतिहास बताना चाहेंगे?",
  ],
  తెలుగు: [
    "మీకు ఏ సమస్య ఉంది?",
    "ఇది ఎప్పుడు మొదలైంది?",
    "ఇది ఎంత ఇబ్బందిగా ఉంది?",
    "ఇది ఎప్పుడూ ఉంటుందా లేదా వచ్చి పోతుందా?",
    "ఇతర లక్షణాలు ఏమైనా ఉన్నాయా?",
    "ప్రస్తుతం ఏ మందులు తీసుకుంటున్నారు?",
    "మీకు అలర్జీలు ఏమైనా ఉన్నాయా?",
    "గత ఆరోగ్య సమస్యలు ఏమైనా ఉన్నాయా?",
  ],
  മലയാളം: [
    "എന്താണ് നിങ്ങളുടെ ആരോഗ്യ പ്രശ്നം?",
    "ഇത് എപ്പോഴാണ് തുടങ്ങിയത്?",
    "ഇത് എത്രത്തോളം ബുദ്ധിമുട്ടിക്കുന്നു?",
    "ഇത് എപ്പോഴും ഉണ്ടോ, ഇടയ്ക്കിടെ വരുന്നതാണോ?",
    "മറ്റ് ലക്ഷണങ്ങൾ ഉണ്ടോ?",
    "ഇപ്പോൾ എന്ത് മരുന്നുകളാണ് കഴിക്കുന്നത്?",
    "അലർജികൾ ഉണ്ടോ?",
    "മുൻ ആരോഗ്യ പ്രശ്നങ്ങൾ പറയാനുണ്ടോ?",
  ],
};
const optionTranslations = {
  தமிழ்: {
    Today: "இன்று",
    "A few days ago": "சில நாட்களுக்கு முன்",
    "A few weeks ago": "சில வாரங்களுக்கு முன்",
    "A long time ago": "நீண்ட காலமாக",
    Mild: "லேசான",
    Moderate: "மிதமான",
    Severe: "கடுமையான",
    "All the time": "எப்போதும்",
    "Comes and goes": "வந்து போகிறது",
    "Getting better": "குணமாகிறது",
    "Getting worse": "அதிகரிக்கிறது",
    Nausea: "குமட்டல்",
    Vomiting: "வாந்தி",
    Fever: "காய்ச்சல்",
    "No other symptoms": "வேறு அறிகுறிகள் இல்லை",
    "Feeling tired": "சோர்வு",
    None: "எதுவும் இல்லை",
    "None known": "தெரிந்த ஒவ்வாமை இல்லை",
    "I have an allergy": "ஒவ்வாமை உள்ளது",
    "I will upload my prescription": "மருந்துச்சீட்டை பதிவேற்றுவேன்",
    "No history to add": "சேர்க்க எதுவும் இல்லை",
    "High blood pressure": "உயர் இரத்த அழுத்தம்",
    Diabetes: "நீரிழிவு",
    "Previous surgery": "முந்தைய அறுவை சிகிச்சை",
    "Something else": "வேறு பிரச்சனை",
    Head: "தலை",
    Chest: "மார்பு",
    Stomach: "வயிறு",
    Back: "முதுகு",
    Legs: "கால்கள்",
    Other: "மற்றவை",
  },
  हिन्दी: {
    Today: "आज",
    "A few days ago": "कुछ दिन पहले",
    "A few weeks ago": "कुछ हफ़्ते पहले",
    "A long time ago": "काफ़ी समय पहले",
    Mild: "हल्का",
    Moderate: "मध्यम",
    Severe: "गंभीर",
    "All the time": "हर समय",
    "Comes and goes": "आता-जाता है",
    "Getting better": "बेहतर हो रहा है",
    "Getting worse": "बढ़ रहा है",
    Nausea: "मतली",
    Vomiting: "उल्टी",
    Fever: "बुखार",
    "No other symptoms": "और कोई लक्षण नहीं",
    "Feeling tired": "थकान",
    None: "कोई नहीं",
    "None known": "कोई ज्ञात एलर्जी नहीं",
    "I have an allergy": "मुझे एलर्जी है",
    "I will upload my prescription": "मैं पर्चा अपलोड करूँगा",
    "No history to add": "कोई इतिहास नहीं",
    "High blood pressure": "उच्च रक्तचाप",
    Diabetes: "मधुमेह",
    "Previous surgery": "पिछला ऑपरेशन",
    "Something else": "कुछ और",
    Head: "सिर",
    Chest: "छाती",
    Stomach: "पेट",
    Back: "पीठ",
    Legs: "पैर",
    Other: "अन्य",
  },
  తెలుగు: {
    Today: "ఈ రోజు",
    "A few days ago": "కొన్ని రోజుల క్రితం",
    "A few weeks ago": "కొన్ని వారాల క్రితం",
    "A long time ago": "చాలా కాలం క్రితం",
    Mild: "తేలికగా",
    Moderate: "మధ్యస్థంగా",
    Severe: "తీవ్రంగా",
    "All the time": "ఎల్లప్పుడూ",
    "Comes and goes": "వచ్చి పోతుంది",
    "Getting better": "మెరుగవుతోంది",
    "Getting worse": "పెరుగుతోంది",
    Nausea: "వికారం",
    Vomiting: "వాంతులు",
    Fever: "జ్వరం",
    "No other symptoms": "ఇతర లక్షణాలు లేవు",
    "Feeling tired": "అలసట",
    None: "ఏమీ లేదు",
    "None known": "తెలిసిన అలర్జీలు లేవు",
    "I have an allergy": "అలర్జీ ఉంది",
    "I will upload my prescription": "ప్రిస్క్రిప్షన్ అప్లోడ్ చేస్తాను",
    "No history to add": "చరిత్ర లేదు",
    "High blood pressure": "అధిక రక్తపోటు",
    Diabetes: "మధుమేహం",
    "Previous surgery": "గత శస్త్రచికిత్స",
    "Something else": "ఇంకేదైనా",
    Head: "తల",
    Chest: "ఛాతీ",
    Stomach: "పొట్ట",
    Back: "వీపు",
    Legs: "కాళ్లు",
    Other: "ఇతర",
  },
  മലയാളം: {
    Today: "ഇന്ന്",
    "A few days ago": "കുറച്ച് ദിവസം മുമ്പ്",
    "A few weeks ago": "കുറച്ച് ആഴ്ച മുമ്പ്",
    "A long time ago": "കുറേ കാലം മുമ്പ്",
    Mild: "നേരിയ",
    Moderate: "മിതമായ",
    Severe: "കടുത്ത",
    "All the time": "എപ്പോഴും",
    "Comes and goes": "ഇടയ്ക്കിടെ",
    "Getting better": "മെച്ചപ്പെടുന്നു",
    "Getting worse": "കൂടുന്നു",
    Nausea: "ഓക്കാനം",
    Vomiting: "ഛർദ്ദി",
    Fever: "പനി",
    "No other symptoms": "മറ്റ് ലക്ഷണങ്ങളില്ല",
    "Feeling tired": "ക്ഷീണം",
    None: "ഒന്നുമില്ല",
    "None known": "അറിയാവുന്ന അലർജികളില്ല",
    "I have an allergy": "അലർജി ഉണ്ട്",
    "I will upload my prescription": "കുറിപ്പടി അപ്‌ലോഡ് ചെയ്യാം",
    "No history to add": "മുൻ പ്രശ്നങ്ങളില്ല",
    "High blood pressure": "ഉയർന്ന രക്തസമ്മർദ്ദം",
    Diabetes: "പ്രമേഹം",
    "Previous surgery": "മുൻ ശസ്ത്രക്രിയ",
    "Something else": "മറ്റെന്തെങ്കിലും",
    Head: "തല",
    Chest: "നെഞ്ച്",
    Stomach: "വയർ",
    Back: "പുറം",
    Legs: "കാലുകൾ",
    Other: "മറ്റുള്ളവ",
  },
};
export const t = (lang, key) => words[lang]?.[key] || words.English[key] || key;
export function localOption(lang, value) {
  const dict = optionTranslations[lang];
  if (!dict) return value;
  if (dict[value]) return dict[value];
  for (const part of ["Head", "Chest", "Stomach", "Back", "Legs"]) {
    if (value.startsWith(part + " "))
      return `${dict[part]} · ${value.endsWith("pain") ? { தமிழ்: "வலி", हिन्दी: "दर्द", తెలుగు: "నొప్పి", മലയാളം: "വേദന" }[lang] : { தமிழ்: "அசௌகரியம்", हिन्दी: "परेशानी", తెలుగు: "అసౌకర్యం", മലയാളം: "അസ്വസ്ഥത" }[lang]}`;
  }
  return value;
}
export const localQuestion = (lang, key, fallback) =>
  questions[lang]?.[
    [
      "complaint",
      "duration",
      "severity",
      "pattern",
      "associatedSymptoms",
      "medication",
      "allergies",
      "medicalHistory",
    ].indexOf(key)
  ] || fallback;
